export const ConfigurationConstants = {
  HEADER_SKIP_LOADER: "Skip-Loader",
  HEADER_CACHE_REQUEST: "Cache-Request"
};
export const API = {
  PROJECTS: (organizationId, userId) => `projects/${organizationId}/${userId}`,
  GETPROJECT: (organizationId, projectId) => `project/${organizationId}/${projectId}`,
  GETCATERGORY: `material/groups`,
  ADDPROJECT: `addProject`,
  UPDATEPROJECT: (organizationId, projectId) => `updateProjectDetails/${organizationId}/${projectId}`,
  RAISEINDENT: projectId => `indent/raise/${projectId}`,
  DELETE: (organizationId, projectId) => `deleteProject/${organizationId}/${projectId}`,
  GETMATERIALSWITHSPECS: `material/materialsSpecs`,
  GETMATERIALSWITHQUANTITY: (organizationId, projectId) => `materials/${organizationId}/${projectId}`,
  GETINDENTLIST: projectId => `indent/list/${projectId}`,
  POSTMATERIALSQUANTITY: (userId, projectId) => `materials/${userId}/${projectId}`,
  GETMATERIALWISE: organizationId => `global/materials/${organizationId}`,
  GETPROJECTWISE: organizationId => `global/projects/${organizationId}`,
  RFQMATERIALS: `rfqMaterials`,
  RFQDETAIL: organizationId => `rfq/list/${organizationId}`,
  RFQPO: (organizationId, rfqId) => `rfq/details/${organizationId}/${rfqId}`,
  RFQADDPO: `po/addPO`,
  GETSUPPLIERS: organizationId => `projects/getsuppliers/${organizationId}`,
  ADDSUPPLIER: organizationId => `projects/addSuppliers/${organizationId}`,
  GETPODETAILLIST: organizationId => `po/detail/list/${organizationId}`,
  GETPODATA: poId => `po/genarate/${poId}`,
  SENDPODATA: `po/updatePO`,
  ADDRFQ: `rfq/addrfq`,
  GETRFQDETAILSUPPLIER: (rfqId, supplierId) => `rfq/details/supplier/${rfqId}/${supplierId}`,
  POSTRFQDETAILSUPPLIER: supplierId => `rfq/addSupplierDetail/${supplierId}`,
  GETAPPROVER: (organizationId, projectId) => `po/users/${organizationId}/${projectId}`,
  POSTADDADDRESS: (type, id) => `address/add/${type}/${id}`,
  GETPOADDADDRESS: (type, id) => `address/get/${type}/${id}`,
  POSTDOCUMENTUPLOAD: `documents/upload`,
  SIGNUP: `api/auth/signup`,
  SIGNIN: `oauth/token`,
  GETISSUETOINDENT: (materialId, projectId) => `materials/updateStock/${materialId}/${projectId}`,
  POSTISSUETOINDENT: materialId => `indent/issueQty/${materialId}`,
  GETSINGLEINDENT: indentId => `indent/detail/${indentId}`,
  GETGRNDETAILS: grnId => `po/view/grn/poDetails/${grnId}`,
  ADDGRN: `po/add/grn`,
  VIEWGRN: (organizationId, purchaseOrderId) => `po/grn/detail/${organizationId}/${purchaseOrderId}`,
  GETRFQVIEW: rfqId => `rfq/view/details/${rfqId}`,
  ROLES: `user/getroles`,
  ALLUSERS: organizationId => `user/getall/${organizationId}`,
  ADDUSER: `user/add`,
  EDITUSER: `user/update/roleproject`,
  DEACTIVATEUSER: userId => `user/delete/${userId}`,
  UPLOADEXCEL: projectId => `bom/materials/fileupload/${projectId}`,
  DELETESUPPLIER: supplierId => `projects/deleteSupplier/${supplierId}`,
  DELETEMATERIAL: (projectId, materialId) => `material/delete/${projectId}/${materialId}`,
  APPROVEREJECTPO: `po/approveRejectPO`,
  GETGENERATEDRFQ: rfqId => `fq/stepper/${rfqId}`,
  DELETEDRAFTEDPO: purchaseOrderId => `po/delete/${purchaseOrderId}`,
  GETSUPPLIERADDRESS: supplierId => `address/get/Supplier/${supplierId}`,
  ADDSUPPLIERADDRESS: supplierId => `address/add/Supplier/${supplierId}`,
  NUMBERTOWORDS: currency => `commons/numtowords/${currency}`,
  GET_USER_PROFILE: USERID => `user/profile/${USERID}`,
  GET_ALL_TRADES: 'all/tades',
  SUBMIT_USER_DETAILS: 'user/update/profile',
  GET_NOTIFICATIONS: userId => `user/notification/${userId}`
};
