export const ErrorCodesConstants = {
    ERROR_HTTP_NO_RESPONSE: 0,
    ERROR_HTTP_UNAUTHORIZED: 401,
    ERROR_HTTP_NO_NETWORK: 1000,
    ERROR_HTTP_NOT_FOUND: 404,
    ERROR_HTTP_UNAUTHORIZED_ROLE: 403,
    ERROR_HTTP_SERVER_ISSUE: 500
}
